SELECT
    'N' as SELECIONADO,
    NFE.*,
    EMIT.ID_EMITENTE_CLIENTE,
    EMIT.RAZAO AS RAZAOSOCIAL_EMITENTE,
    EMIT.FANTASIA AS NOMEFANTASIA_EMITENTE,
    EMIT.CPF_CNPJ AS CPFCNPJ_EMITENTE,
    CF.CFOP AS CFOP_NOTAFISCAL,
    EST.SIGLA AS SIGLA_ESTADO_EMITENTE,
    EMIT.ENDERECO AS ENDERECO_EMITENTE,
    EMIT.BAIRRO AS BAIRRO_EMITENTE,
    EMIT.NUMERO AS NUMERO_EMITENTE,
    EST.CODIGO_IBGE AS CODIGOIBGE_ESTADO,
    CID.CODIGO_IBGE AS CODIGOIBGE_CIDADE,
    EMIT.COMPLEMENTO AS COMPLEMENTO_EMITENTE,
    EMIT.CEP AS CEP_EMITENTE,
    CID.NOME AS NOMECIDADE_EMITENTE,
    EMIT.CONTATO AS CONTATO_EMITENTE,
    EMIT.INSCRICAO_ESTADUAL AS INSCRICAOESTADUAL_EMITENTE,
    OP.DESCRICAO AS DESCRICAO_OPERACAO
FROM
    NOTA_FISCAL_ENTRADA NFE
    LEFT JOIN EMITENTE EMIT ON EMIT.ID_EMITENTE = NFE.ID_EMITENTE
    LEFT JOIN ESTADO EST ON EST.ID_ESTADO = EMIT.ID_ESTADO
    LEFT JOIN CIDADE CID ON CID.ID_CIDADE = EMIT.ID_CIDADE
    LEFT JOIN CFOP CF ON CF.ID_CFOP = NFE.ID_CFOP
    LEFT JOIN EMPRESA E ON E.ID_EMPRESA = NFE.ID_EMPRESA
    LEFT JOIN OPERACAO OP ON OP.ID_OPERACAO = NFE.ID_OPERACAO
WHERE
    NFE.ID_EMPRESA = 1
    AND NFE.STATUS_NF LIKE '%'
    AND NFE.DTHR_NOTAFISCAL BETWEEN ('2024-01-01 00:00:01')
    AND ('2024-01-31 23:59:59')